# Generated by Django 2.0.3 on 2018-03-19 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20180319_1745'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_logon',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
